version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gostack_gobaber
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - postgres
volumes:
  dbdata: